---
- name: "install openssl"
  package:
    name: openssl
    state: latest

- name: "Create cache dir"
  file:
    name: "{{ juseppe_cert_dir }}"
    state: directory
    owner: root
    group: root

- name: "Generate private key"
  shell: >
    openssl genrsa -out uc.key 2048
  args:
    chdir: "{{ juseppe_cert_dir }}"

- name: "Generate certificate based on private key"
  shell: >
    openssl req -nodes -x509 -new \
    -key uc.key \
    -out uc.crt \
    -days 1056 \
    -subj "/C=/ST=Update-Center/L=Juseppe/O=Juseppe"EN
  args:
    chdir: "{{ juseppe_cert_dir }}"
